config/routes.rb
FbFaggruppe::Application.routes.draw do

  resources :oauth , :controller => 'oauth' do 
    collection do
      get :start
      get :callback
    end
  end

  root :to => 'oauth#start'
  
  match 'home' => 'pages#home', :as => :home
  match 'friends' => 'pages#friends', :as => :friends
  match 'publish' => 'pages#publish', :as => :publish
  
  
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def client
    @client ||= FBGraph::Client.new(:client_id => 'xxx',
                                   :secret_id => 'xxx' , 
                                   :token => session[:access_token])
  end
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  def start
    redirect_to client.authorization.authorize_url(
      :redirect_uri => callback_oauth_index_url, 
      :scope => 'email,user_photos,friends_photos,user_photo_video_tags,publish_stream'
    )
  end
  
  def callback
    access_token = client.authorization.process_callback(params[:code], :redirect_uri => callback_oauth_index_url)
    session[:access_token] = access_token
    
    redirect_to home_url
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @me = client.selection.me.info!
  end
  
  def friends
    @friends = client.selection.me.friends.info!.data
  end
  
  def publish
    client.selection.me.feed.publish!(:message => params[:message]) if params[:message]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FbFaggruppe</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<!--
 <%= link_to "Home", home_path %> | <%= link_to "Friends", friends_path %> | <%= link_to "Publish to my wall", publish_path %>
 -->
<%= yield %>

</body>
</html>

app/views/pages/friends.html.erb
<h2>My Friends</h2>

<ul>
  <% @friends.each do |friend| %>
    <li><%= friend.name %></li>
  <% end %>
</ul>

app/views/pages/home.html.erb
<h1>Velkommen <%= @me.first_name %> <%= @me.last_name %></h1>

app/views/pages/publish.html.erb
<form action="<%= publish_path %>" method="GET">
  <input type="text" name="message"><br/>
  <input type="submit">
</form>